const fs = require('fs');

const missingQuestions = {
  'b12': [
    {
      q: "Dizayn düşüncəsi (Design Thinking) və sistemli yanaşma",
      a: "**Dizayn düşüncəsi (Design Thinking)** — problemləri həll etmək, innovasiya yaratmaq və istifadəçi ehtiyaclarını ödəmək üçün dizaynerlərin metodologiyasını və yanaşmasını tətbiq edən sistemli prosesdir. Stanford d.School və IDEO-nun metodologiyası əsasında formalaşıb.\n\n**Dizayn düşüncəsinin 5 mərhələsi (Stanford d.School):**\n1) **Empatiya (Empathize)** — istifadəçini anlamaq, müşahidə, müsahibə, etnografiya\n2) **Tərif (Define)** — problemin aydın ifadəsi, POV (Point of View), istifadəçi ehtiyacları\n3) **İdeya (Ideate)** — brainstorming, mind mapping, SCAMPER, analogiya, ən pis ideya\n4) **Prototip (Prototype)** — fiziki, rəqəmsal, kağız, rol oyunu, storyboard\n5) **Sınaq (Test)** — istifadəçi sınağı, A/B sınaq, geri əlaqə, iterasiya\n\n**Dizayn düşüncəsinin prinsipləri:**\n- **İnsan mərkəzli (Human-centered)** — istifadəçi ehtiyacları, emosiya, motivasiya\n- **Prototip əsaslı (Prototype-driven)** — tez sınaq, səhvə icazə, öyrənmə\n- **İterativ (Iterative)** — təkrarlayan proses, təkmilləşdirmə\n- **Əməkdaşlıq (Collaborative)** — multidissiplinar komanda, fərqli baxışlar\n- **Vizual (Visual)** — eskiz, diaqram, model, fiziki prototip\n- **Eksperimental (Experimental)** — sınaq, kəşf, qeyri-müəyyənliklə işləmə\n\n**Sistemli yanaşma (Systems Thinking):**\n- **Sistem** — bir-birinə bağlı elementlər, mürəkkəb əlaqələr, feedback döngüləri\n- **Sistemli yanaşma** — hissələri ayrıca deyil, bütün olaraq analiz etmək\n- **Causal Loop Diagrams** — səbəb-nəticə əlaqələri, feedback\n- **Stock and Flow** — ehtiyat, axın, tarazlıq\n- **Leverage Points** — sistemi dəyişmək üçün ən təsirli nöqtələr\n\n**Dizayn düşüncəsi + sistemli yanaşma:**\n- İnsan mərkəzli + sistemli baxış = davamlı, miqyaslanan həllər\n- Təkcə simptom deyil, kök səbəbi həll etmək\n- Stakeholder mapping, ecosystem mapping\n- Sistemli innovasiya, sosial innovasiya",
      k: ["dizayn düşüncəsi", "design thinking", "sistemli yanaşma", "prototip", "empatiya"]
    }
  ],
  'b13': [
    {
      q: "Dizayn strategiyası və brend inteqrasiyası",
      a: "**Dizayn strategiyası (Design Strategy)** — dizayn fəaliyyətinin biznes məqsədləri, bazar tələbləri və istifadəçi ehtiyacları ilə uyğunlaşdırılması üçün strateji planlaşdırma prosesidir. **Brend inteqrasiyası** isə dizaynın bütün təmas nöqtələrində (touchpoints) vahid brend təcrübəsi yaratmasıdır.\n\n**Dizayn strategiyasının komponentləri:**\n1) **Brend strategiyası** — missiya, vizyon, dəyərlər, məqsəd kütlə (target audience)\n2) **Bazar strategiyası** — seqmentləşdirmə, fərqləndirmə, pozisiya\n3) **Məhsul strategiyası** — portfel, roadmap, innovasiya, lifecycle\n4) **Təcrübə strategiyası** — CX, UX, service, omnichannel\n5) **Əməliyyat strategiyası** — proses, səmərəlilik, keyfiyyət, davamlılıq\n\n**Brend inteqrasiyasının səviyyələri:**\n- **Strateji** — brend dəyər təklifi, pozisiya, arqetip\n- **Vizual** — loqo, tipoqrafiya, rəng, forma, qablaşdırma, retail design\n- **Verbal** — ton, dil, mesaj, hekayə, adlandırma\n- **Davranış** — müştəri xidməti, satış, istifadəçi təcrübəsi, sosial media\n- **Məkan** — ofis, mağaza, sərgi, virtual məkan\n- **Məhsul** — form, funksiya, material, interfeys, CMF\n\n**Dizayn + brend inteqrasiya modelləri:**\n1) **Aaker-in brend aktiv modeli** — brend fərqliyi, assosiasiya, reaksiya, münasibət\n2) **Kapferer-in brend prisması** — fizika, şəxsiyyət, mədəniyyət, əlaqə, əks, özünütəsvir\n3) **Brand Touchpoint Wheel** — bütün təmas nöqtələrinin dizaynı\n4) **Service Blueprint** — ön səhnə, arxa səhnə, dəstək prosesləri\n\n**Dizayn strategiyasının icra mərhələləri:**\n1. Araşdırma (bazar, istifadəçi, rəqabət, trend)\n2. Strategiya (məqsəd, pozisiya, fərqləndirmə, kpi)\n3. Konsept (dizayn konseptləri, brend platforması)\n4. İnkişaf (detallı dizayn, prototip, sınaq)\n5. İmplementasiya (istehsal, launch, marketing, ölçmə)",
      k: ["dizayn strategiyası", "brend inteqrasiyası", "brend", "touchpoint", "service blueprint"]
    },
    {
      q: "Təcrübə dizaynı (Experience Design) və istifadəçi mərkəzli yanaşma",
      a: "**Təcrübə dizaynı (Experience Design / XD)** — istifadəçinin məhsul, xidmət, sistem və ya mühitlə bütün təcrübəsini strateji şəkildə dizayn etmə prosesidir. **İstifadəçi mərkəzli yanaşma (User-Centered Design / UCD)** — dizayn qərarlarının istifadəçi ehtiyacları, davranışları və rəyləri əsasında verilməsidir.\n\n**Təcrübə dizaynının növləri:**\n1) **User Experience (UX)** — rəqəmsal məhsul, veb, app, interfeys\n2) **Customer Experience (CX)** — bütün müştəri təcrübəsi, brend, xidmət\n3) **Service Experience (SX)** — xidmət təcrübəsi, personal, proses, mühit\n4) **Brand Experience (BX)** — brendlə bütün təmaslar, emosiya, yaddaş\n5) **Employee Experience (EX)** — işçi təcrübəsi, ofis, mədəniyyət, HR\n6) **Spatial Experience** — fiziki məkan, retail, ofis, sərgi\n\n**İstifadəçi mərkəzli dizayn prinsipləri (ISO 9241-210):**\n1) Aktiv istifadəçi iştirakı\n2) Uyğun funksional tələblər\n3) Dizayn iterasiyası\n4) Multidissiplinar komanda\n5) Sosial və istifadəçi konteksti nəzərə almaq\n\n**Təcrübə dizaynı metodları:**\n- **Persona** — tipik istifadəçi profili, ehtiyac, motivasiya, senari\n- **Customer Journey Map (CJM)** — təmas nöqtələri, emosiya, ağrı nöqtələri, fürsətlər\n- **Empathy Map** — istifadəçi nə deyir, düşünür, hiss edir, edir\n- **Service Blueprint** — ön səhnə, arxa səhnə, dəstək prosesləri, fiziki sübutlar\n- **Touchpoint Analysis** — bütün təmas nöqtələrinin qiymətləndirilməsi\n- **Moment of Truth** — həlledici təmas nöqtələri\n\n**Təcrübə dizaynının ölçülməsi:**\n- **NPS (Net Promoter Score)** — tövsiyə ehtimalı\n- **CSAT (Customer Satisfaction)** — məmnunluq\n- **CES (Customer Effort Score)** — sərf olunan səy\n- **SUS (System Usability Scale)** — sistem istifadə oluna bilirliyi\n- **HEART (Google)** — Happiness, Engagement, Adoption, Retention, Task success",
      k: ["təcrübə dizaynı", "istifadəçi mərkəzli", "UX", "CX", "service blueprint"]
    }
  ],
  'b14': [
    {
      q: "Təşkilati dizaynın gələcəyi və trendləri",
      a: "**Təşkilati dizaynın gələcəyi** — texnoloji, sosial, iqtisadi və ətraf mühit dəyişikliklərinin təşkilatların quruluşunu, proseslərini və mədəniyyətini necə təsir etdiyini proqnozlaşdırmaq və buna uyğun hazırlıq görmək deməkdir.\n\n**Təşkilati dizaynın gələcək trendləri:**\n\n**1) AI və avtomatlaşdırma təsiri:**\n- **Augmented Management** — AI dəstəkli qərar, proqnoz, optimallaşdırma\n- **Algorithmic Management** — alqoritm tərəfindən tapşırıq, nəzarət, qiymətləndirmə\n- **Human-AI Collaboration** — insanı əvəz etmək deyil, gücləndirmək (augmentation)\n- **Yeni rol və bacarıqlar** — AI etikası, data literacy, prompt engineering\n- **Təşkilat strukturu dəyişikliyi** — az ierarxiya, daha çox network, platforma\n\n**2) Uzaq və hibrid iş modeli:**\n- **Distributed teams** — coğrafi baxımdan dağınıq komandalar\n- **Asynchronous work** — sinxron olmayan əməkdaşlıq, vaxt zonası fərqi\n- **Digital-first workplace** — rəqəmsal infrastruktur, VR/VR ofis, metaverse\n- **Work from anywhere** — ofis, ev, coworking, hibrid\n- **Nəticə əsaslı idarəetmə** — vaxt deyil, output ölçüsü\n\n**3) Çevik və adaptiv təşkilatlar:**\n- **Agile at scale** — SAFe, LeSS, Spotify modeli, tribe-squad\n- **Teal Organization (Laloux)** — özünüidarə, bütövlük, məqsəd\n- **Holacracy** — rola əsaslanan, iyerarxiyasız idarəetmə\n- **Sociocracy** — dairəvi struktur, konsent qərarları\n- **Adaptive Enterprise** — real-time data, sürətli adaptasiya, scenario planning\n\n**4) ESG və davamlılıq:**\n- **Carbon-neutral operations** — karbon neytral əməliyyatlar\n- **Circular organization** — döngüvi iqtisadiyyat, tullantısız\n- **Social impact measurement** — sosial təsir ölçməsi\n- **Stakeholder capitalism** — səhmdar deyil, bütün maraqlı tərəflər\n- **B Corp, Benefit Corporation** — mənfəət + məqsəd\n\n**5) Yeni idarəetmə modelləri:**\n- **Platform-based organization** — daxili platforma, eko-sistem, API\n- **Ecosystem orchestration** — ekosistem orkestrasiyası\n- **Zero-based organization** — sıfırdan struktur dizaynı\n- **Liquid workforce** — maye işçi qüvvəsi, gig economy, frilans, platforma\n- **Talent marketplace** — daxili istedad bazar",
      k: ["təşkilati dizayn", "gələcək trendlər", "AI", "hibrid iş", "çevik təşkilat"]
    },
    {
      q: "Dizayn əsaslarının icrası və performans ölçüsü",
      a: "**Dizayn əsaslarının icrası (Implementation)** — təşkilati dizayn qərarlarının əməliyyat səviyyəsində tətbiqi, proseslərə, struktura, sistemlərə və davranışlara inteqrasiyasıdır. **Performans ölçüsü** isə dizaynın effektivliyini, səmərəliliyini və nəticələrini ölçmək üçün metodologiyalar və göstəricilər toplusudur.\n\n**Dizayn əsaslarının icra mərhələləri:**\n1) **Strateji hizalanma (Alignment)** — dizayn, biznes, istifadəçi, texnologiya hizalanması\n2) **Pilot (Pilot)** — kiçik miqyaslı sınaq, prototip, proof of concept\n3) **Rolout (Rollout)** — mərhələli yayım, change management, training\n4) **İnteqrasiya (Integration)** — sistem, proses, mədəniyyət, IT inteqrasiyası\n5) **Optimallaşdırma (Optimization)** — data-driven təkmilləşmə, iterasiya\n6) **Ölçmə (Measurement)** — KPI, metric, dashboard, reporting\n\n**İcra çətinlikləri və həlli:**\n- **Müqavimət (Resistance)** — change management, kommunikasiya, fayda göstərmə\n- **Silo (Silo effect)** — cross-functional komanda, OKR, bütövlük mədəniyyəti\n- **Resurs çatışmazlığı** — prioritet, büdcə, vaxt, insan\n- **Sistem uygunsuzluğu** — legacy system, API, inteqrasiya, data migration\n- **Liderlik dəstəyi** — executive sponsor, CDO, design council\n- **Ölçmə çətinliyi** — subjective vs objective, qualitative vs quantitative\n\n**Dizayn performans ölçmə modelləri:**\n\n**1) Balanced Scorecard (Kaplan & Norton):**\n- Finansal (revenue, margin, ROI, market share)\n- Müştəri (satisfaction, retention, NPS, acquisition)\n- Daxili proses (efficiency, quality, time, cost)\n- Öyrənmə və inkişaf (innovation, employee satisfaction, skills)\n\n**2) Design Maturity Model:**\n- **Level 1:** No design (design yoxdur)\n- **Level 2:** Design as styling (görünüş, estetika)\n- **Level 3:** Design as process (proses, metodologiya)\n- **Level 4:** Design as strategy (strateji, innovasiya)\n- **Level 5:** Design as culture (mədəniyyət, DNA, hər şeydən əvvəl dizayn)\n\n**3) Design Value Framework (DMI):**\n- **Design Value Index** — dizaynə investisiya edən şirkətlərin bazar performansı\n- **Design ROI** — dizayn investisiyasının gəliri\n- **Design-driven growth** — dizayn əsaslı böyümə\n\n**4) McKinsey Design Index:**\n- Analitik (data-driven, test, iterate)\n- Cross-functional (multidissiplinar, bütövlük)\n- User-centric (istifadəçi, empatiya, sınaq)\n- Empowered (liderlik, səlahiyyət, autonomiya)",
      k: ["dizayn icrası", "performans ölçüsü", "balanced scorecard", "design maturity", "KPI"]
    },
    {
      q: "Təşkilati əməkdaşlıq və komanda dinamikası",
      a: "**Təşkilati əməkdaşlıq (Organizational Collaboration)** — fərqli şöbə, komanda, səviyyə və təşkilatlar arasında ortaq məqsəd ətrafında birgə çalışma prosesidir. **Komanda dinamikası (Team Dynamics)** — komanda üzvləri arasında əlaqə, qarşılıqlı təsir, emosiya, davranış və proseslərin nəticə verən şəkildə idarə olunmasıdır.\n\n**Təşkilati əməkdaşlıq növləri:**\n1) **Daxili əməkdaşlıq (Internal)** — şöbəarası, cross-functional, layihə əsaslı\n2) **Xarici əməkdaşlıq (External)** — təchizatçı, müştəri, konsaltinq, akademiya\n3) **Strateji əməkdaşlıq (Strategic)** — alliance, joint venture, konsorsium\n4) **Rəqabətli əməkdaşlıq (Coopetition)** — rəqiblər arasında birgə fəaliyyət (standard, platforma)\n5) **Ekosistem əməkdaşlığı (Ecosystem)** — platforma, API, marketplace, developer community\n\n**Komanda dinamikasının faktörləri (Tuckman, 1965):**\n1) **Forming (Yaranma)** — tanışlıq, qaydalar, rollar, müəyyənlik\n2) **Storming (Toqquşma)** — fikir ayrılığı, müqavimət, liderlik yarışı\n3) **Norming (Normalaşma)** — razılaşma, proses, inam, koheziya\n4) **Performing (Performans)** — yüksək səmərəlilik, autonomiya, qarşılıqlı asılılıq\n5) **Adjourning (Sonlanma)** — layihə bitişi, təcrübə, dağılma\n\n**Komanda effektivliyinin faktörləri (Google Aristotle Project):**\n1) **Psychological safety** — təhlükəsizlik, səhvə icazə, risk götürmə\n2) **Dependability** — etibarlılıq, tapşırığı vaxtında, keyfiyyətli yerinə yetirmə\n3) **Structure and clarity** — aydın rol, məqsəd, proses, ölçü\n4) **Meaning of work** — işin mənası, dəyər, motivasiya\n5) **Impact of work** — təsir, nəticə, fayda, tanınma\n\n**Təşkilati əməkdaşlıq vasitələri:**\n- **OKR (Objectives and Key Results)** — ortaq məqsəd, ölçülü nəticə\n- **Cross-functional teams** — müxtəlif funksiyalar bir komanda\n- **Communities of Practice (CoP)** — praktika cəmiyyəti, bilik mübadiləsi\n- **Agile ceremonies** — daily standup, sprint planning, retrospective, demo\n- **Digital collaboration tools** — Slack, Teams, Miro, Figma, Notion, Jira\n- **Open office / Hot desking** — fiziki əməkdaşlıq, informasiya axını\n- **Job rotation / Secondment** — vəzifə rotasiyası, müxtəlif təcrübə",
      k: ["təşkilati əməkdaşlıq", "komanda dinamikası", "Tuckman", "Google Aristotle", "cross-functional"]
    }
  ],
  'b15': [
    {
      q: "Dizayn prosesinin inteqrasiyası və əlaqələndirmə",
      a: "**Dizayn prosesinin inteqrasiyası (Integration)** — dizayn fəaliyyətinin biznes, texnologiya, marketinq, istehsal, təchizat və digər funksiyalarla bütövləşdirilməsidir. **Əlaqələndirmə (Coordination)** — bu inteqrasiyanın səmərəli şəkildə idarə olunması, kommunikasiya, qərar və icra proseslərinin uyğunlaşdırılmasıdır.\n\n**Dizayn inteqrasiyasının səviyyələri:**\n1) **Strateji inteqrasiya** — dizayn, brend, biznes strategiya bütövlüyü\n2) **Taktiki inteqrasiya** — layihə, proses, metodologiya, tool\n3) **Əməliyyat inteqrasiya** — gündəlik iş, sənəd, məlumat, kommunikasiya\n4) **Sistem inteqrasiya** — IT, software, hardware, data, API\n5) **Mədəniyyət inteqrasiya** — dəyər, norma, davranış, mədəniyyət\n\n**Əlaqələndirmə mexanizmləri:**\n- **Rəhbərlik (Direct supervision)** — birbaşa nəzarət, icraçı rəhbər\n- **Standartlaşdırma (Standardization)** — proses, output, bacarıq, norma\n- **Təkrar proqramlaşdırma (Mutual adjustment)** — qarşılıqlı tənzimləmə, kommunikasiya\n- **Ortaq dil (Shared language)** — termin, konsept, model, framework\n- **Ortaq sistem (Shared system)** — ERP, PLM, CRM, DAM, PIM\n- **Ortaq məkan (Shared space)** — ofis, studio, fab, virtual məkan\n- **Ortaq vaxt (Shared time)** — iclas, standup, review, sprint\n- **Ortaq məqsəd (Shared goal)** — OKR, KPI, layihə məqsədi, brend vizyonu\n\n**Dizayn-inteqrasiya modelləri:**\n1) **Design-as-a-Service (DaaS)** — dizayn xidməti, mərhələli, sifariş əsasında\n2) **Embedded design** — dizayner digər komandaya yerləşdirilib\n3) **Design ops** — dizayn əməliyyatları, infrastruktur, sistem, tool\n4) **Design system** — komponent, pattern, guideline, library, token\n5) **Design council** — strateji dizayn qərarları, liderlik, səlahiyyət\n6) **Design sprint** — 5 günlük intensiv, komanda, problem, prototip, sınaq\n\n**Əlaqələndirmə çətinlikləri:**\n- **Silo (Silo effect)** — şöbə mərkəzli, məlumat paylaşmamaq\n- **Dil fərqi** — texniki, dizayn, biznes, marketinq termin fərqi\n- **Prioritet fərqi** — fərqli məqsəd, KPI, vaxt, büdcə\n- **Mədəniyyət fərqi** — fərqli iş üslubu, sürət, risk, innovasiya\n- **Alət fərqi** — fərqli software, format, versiya, platforma\n- **Coğrafi fərq** — uzaq komanda, vaxt zonası, dil, mədəniyyət\n- **Səlahiyyət fərqi** — kimə hesabat verir, qərar hüququ, büdcə",
      k: ["dizayn inteqrasiyası", "əlaqələndirmə", "silo", "design ops", "design system"]
    },
    {
      q: "Təşkilati dizaynın qiymətləndirilməsi və təkmilləşdirilməsi",
      a: "**Təşkilati dizaynın qiymətləndirilməsi (Evaluation)** — təşkilatın strukturunun, proseslərinin, mədəniyyətinin və nəticələrinin sistemli şəkildə analizi, müqayisəsi və effektivliyinin ölçülməsidir. **Təkmilləşdirilməsi (Improvement)** — qiymətləndirmə nəticələrinə əsaslanan, strateji dəyişikliklər, proses optimallaşdırması və struktur yenilənməsi prosesidir.\n\n**Qiymətləndirmə modelləri və çərçivələri:**\n\n**1) McKinsey 7S Modeli:**\n- **Hard (sərt):** Strategiya, Struktur, Sistemlər\n- **Soft (yumşaq):** Shared values, Skills, Style, Staff\n- 7S bütövlüyü, balans, uyğunluq\n\n**2) Nadler-Tushman Uyğunluq Modeli (Congruence Model):**\n- Daxili uyğunluq (task, individual, formal, informal)\n- Xarici uyğunluq (strateji, mühit, texnologiya)\n- Uyğunsuzluq = performans düşüklüyü, çətinlik, çatışmamazlıq\n\n**3) Weisbord-in 6 qutu modeli:**\n- Məqsəd, struktur, əlaqələr, mükafat, liderlik, faydalı mexanizm\n\n**4) TQM (Total Quality Management):**\n- Davamlı təkmilləşmə (Kaizen)\n- Müştəri mərkəzli, bütün komanda, proses idarəetməsi\n- PDCA (Plan-Do-Check-Act)\n- 6 Sigma (DMAIC: Define, Measure, Analyze, Improve, Control)\n\n**5) EFQM (European Foundation for Quality Management):**\n- Enabler (liderlik, strategiya, komanda, resurs, proses)\n- Nəticə (müştəri, işçi, cəmiyyət, biznes)\n\n**Qiymətləndirmə metodları:**\n- **SWOT Analizi** — güclü tərəflər, zəif tərəflər, fürsətlər, təhlükələr\n- **Gap Analizi** — hazırkı vs hədəf vəziyyət, aradakı boşluq\n- **Benchmarking** — əvvəlcədən müəyyən edilmiş standartlarla müqayisə\n- **Balanced Scorecard** — maliyyə, müştəri, daxili proses, öyrənmə\n- **Organizational Network Analysis (ONA)** — əlaqə, təsir, informasiya axını\n- **Employee surveys / Engagement studies** — işçi mənfəətləri, qaneetmə, motivasiya\n- **360-dərəcə rəy** — hərtərəfli rəy, rəhbər, həmkar, özü, müştəri\n\n**Təkmilləşdirmə yanaşmaları:**\n- **Kaizen (Davamlı təkmilləşmə)** — kiçik, addım-addım, hər gün, hər kəs\n- **Reengineering (Radikal yenidənqurma)** — kökündən, sürətli, qlobal (Hammer & Champy)\n- **Lean Management** — tullantıları aradan qaldırmaq, səmərəlilik (Toyota)\n- **Agile Transformation** — çeviklik, adaptivlik, iterasiya, müştəri mərkəzli\n- **Digital Transformation** — rəqəmsal texnologiya, data, AI, avtomatlaşdırma\n- **Culture Change** — mədəniyyət, dəyər, davranış, adət dəyişikliyi\n- **Structural Change** — struktur, iyerarxiya, komanda, səlahiyyət",
      k: ["təşkilati dizayn", "qiymətləndirmə", "təkmilləşmə", "McKinsey 7S", "Kaizen"]
    }
  ]
};

for (const [bilet, questions] of Object.entries(missingQuestions)) {
  const file = `scripts/teskilati_${bilet}.json`;
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  
  // Add missing questions
  for (const q of questions) {
    data.push(q);
  }
  
  // Ensure we have exactly 5 questions
  if (data.length !== 5) {
    console.error(`Warning: ${bilet} has ${data.length} questions, expected 5`);
  }
  
  fs.writeFileSync(file, JSON.stringify(data, null, 2));
  console.log(`${bilet} updated to ${data.length} questions`);
}
